"""add_vendor_biz_fields_and_patient_biz_info

Revision ID: 4bd10ba2db65
Revises: 58af9760b425
Create Date: 2026-03-29 08:55:10.570318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd10ba2db65'
down_revision: Union[str, Sequence[str], None] = '58af9760b425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_biz_info',
    sa.Column('pbi_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pat_id', sa.Integer(), nullable=False),
    sa.Column('biz_name', sa.String(), nullable=True),
    sa.Column('biz_rep_name', sa.String(), nullable=True),
    sa.Column('biz_address', sa.String(), nullable=True),
    sa.Column('biz_type', sa.String(), nullable=True),
    sa.Column('biz_item', sa.String(), nullable=True),
    sa.Column('biz_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['pat_id'], ['patients.pat_id'], ),
    sa.PrimaryKeyConstraint('pbi_id'),
    sa.UniqueConstraint('pat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_biz_info')
    # ### end Alembic commands ###
