"""add_patient_biz_num_columns

Revision ID: 58af9760b425
Revises: a1b2c3d4e5f6
Create Date: 2026-03-28 16:15:53.734150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58af9760b425'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uses_biz_num', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('biz_num', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('biz_num')
        batch_op.drop_column('uses_biz_num')

    # ### end Alembic commands ###
