"""add_vendor_biz_detail_fields

Revision ID: 6ed17c42ba98
Revises: 4bd10ba2db65
Create Date: 2026-03-29 08:55:31.641733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed17c42ba98'
down_revision: Union[str, Sequence[str], None] = '4bd10ba2db65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: patient_biz_info는 runtime DB 소속 — onboarding 마이그레이션에서 제외
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rep_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('biz_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('biz_item', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('biz_item')
        batch_op.drop_column('biz_type')
        batch_op.drop_column('address')
        batch_op.drop_column('rep_name')

    # NOTE: patient_biz_info는 runtime DB 소속 — onboarding 마이그레이션에서 제외
    # ### end Alembic commands ###
