"""baseline_onboarding

Revision ID: 7a5f3ce7f94b
Revises: 
Create Date: 2026-03-28 08:17:14.846687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a5f3ce7f94b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_num', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_operators_phone_num', ['phone_num'])

    with op.batch_alter_table('security_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_snooze_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_settings', schema=None) as batch_op:
        batch_op.drop_column('password_snooze_until')

    with op.batch_alter_table('operators', schema=None) as batch_op:
        batch_op.drop_constraint('uq_operators_phone_num', type_='unique')
        batch_op.drop_column('phone_num')

    # ### end Alembic commands ###
