"""add_runtime_indexes

Revision ID: f3e92092455d
Revises: 7a5f3ce7f94b
Create Date: 2026-03-28 08:18:31.464616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e92092455d'
down_revision: Union[str, Sequence[str], None] = '7a5f3ce7f94b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('op_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('completed_steps', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    with op.batch_alter_table('workflow_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_sessions_op_id'), ['op_id'], unique=False)

    with op.batch_alter_table('extracted_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracted_data_doc_id'), ['doc_id'], unique=False)

    with op.batch_alter_table('patient_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_documents_doc_type'), ['doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_documents_pat_id'), ['pat_id'], unique=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_pat_name'), ['pat_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_reg_num_front'), ['reg_num_front'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_reg_num_front'))
        batch_op.drop_index(batch_op.f('ix_patients_pat_name'))

    with op.batch_alter_table('patient_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_documents_pat_id'))
        batch_op.drop_index(batch_op.f('ix_patient_documents_doc_type'))

    with op.batch_alter_table('extracted_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_data_doc_id'))

    with op.batch_alter_table('workflow_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_sessions_op_id'))

    op.drop_table('workflow_sessions')
    # ### end Alembic commands ###
